Repository Eastrall/Rhisis, pull requests merged in 2019-11, with the labels that each got.

#276 Update project to .NET Core 3
  .travis.yml
  README.md
  src/Rhisis.CLI/Rhisis.CLI.csproj
  src/Rhisis.Cluster/Rhisis.Cluster.csproj
  src/Rhisis.Core/Rhisis.Core.csproj
  src/Rhisis.Database/Rhisis.Database.csproj
  src/Rhisis.Login/Rhisis.Login.csproj
  src/Rhisis.World/Rhisis.World.csproj
  test/Rhisis.Cluster.Tests/Rhisis.Cluster.Tests.csproj
  test/Rhisis.Core.Tests/Rhisis.Core.Tests.csproj
  test/Rhisis.Login.Tests/Rhisis.Login.Tests.csproj
  test/Rhisis.World.Tests/Rhisis.World.Tests.csproj
Labels: enhancement

#277 Update entity framework core to v3.0 and fix inventory save process
  src/Rhisis.CLI/Rhisis.CLI.csproj
  src/Rhisis.Cluster/Handlers/CharacterHandler.cs
  src/Rhisis.Core/Rhisis.Core.csproj
  src/Rhisis.Database/Repositories/Implementation/CharacterRepository.cs
  src/Rhisis.Database/Repositories/Implementation/ItemRepository.cs
  src/Rhisis.Database/Repositories/Implementation/MailRepository.cs
  src/Rhisis.Database/Repositories/Implementation/ShortcutRepository.cs
  src/Rhisis.Database/Repositories/Implementation/UserRepository.cs
  src/Rhisis.Database/Repositories/RepositoryBase.cs
  src/Rhisis.Database/Rhisis.Database.csproj
  src/Rhisis.Network/Rhisis.Network.csproj
  src/Rhisis.World/Game/Factories/IItemFactory.cs
  src/Rhisis.World/Game/Factories/Internal/ItemFactory.cs
  src/Rhisis.World/Game/Structures/Item.cs
  src/Rhisis.World/Handlers/PlayerHandler.cs
  src/Rhisis.World/Systems/Inventory/IInventorySystem.cs
  src/Rhisis.World/Systems/Inventory/InventorySystem.cs
  src/Rhisis.World/Systems/PlayerData/PlayerDataSystem.cs
Labels: bug, critical

#278 Delete Item from Inventory & fixing error when displaying SFX object's at DecreaseItem()
  src/Rhisis.Network/Packets/World/RemoveInventoryItemPacket.cs
  src/Rhisis.World/Handlers/InventoryHandler.cs
  src/Rhisis.World/Systems/Inventory/InventoryItemUsage.cs
Labels: bug, enhancement

#281 Gives to himself exp via Debug Panel as a GM/Admin
  src/Rhisis.Network/Packets/World/ExperiencePacket.cs
  src/Rhisis.World/Handlers/SendExpServerHandler.cs
Labels: enhancement, rhisis-world-server

#282 updated default port for worldserver
  src/Rhisis.Core/Structures/Configuration/World/WorldConfiguration.cs
Labels: enhancement
